// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv7Ppug_aXXYCqp1MIMwzF0F2XupYhSrs',
    appId: '1:667998787835:web:386e5df61bfdb9a38f385e',
    messagingSenderId: '667998787835',
    projectId: 'alaa-3f713',
    authDomain: 'alaa-3f713.firebaseapp.com',
    storageBucket: 'alaa-3f713.firebasestorage.app',
    measurementId: 'G-56W0C68M3P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjKa7Q2Iphvdh30XLLDPeTMRfpf-2EsQE',
    appId: '1:667998787835:android:4f1021568da02a088f385e',
    messagingSenderId: '667998787835',
    projectId: 'alaa-3f713',
    storageBucket: 'alaa-3f713.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBQVnP14wCoLKxtS7wIQsGkvfRn1iCT8Y',
    appId: '1:667998787835:ios:7a9a0103c1fc6b538f385e',
    messagingSenderId: '667998787835',
    projectId: 'alaa-3f713',
    storageBucket: 'alaa-3f713.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBQVnP14wCoLKxtS7wIQsGkvfRn1iCT8Y',
    appId: '1:667998787835:ios:7a9a0103c1fc6b538f385e',
    messagingSenderId: '667998787835',
    projectId: 'alaa-3f713',
    storageBucket: 'alaa-3f713.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAv7Ppug_aXXYCqp1MIMwzF0F2XupYhSrs',
    appId: '1:667998787835:web:8a77f215d81ac33f8f385e',
    messagingSenderId: '667998787835',
    projectId: 'alaa-3f713',
    authDomain: 'alaa-3f713.firebaseapp.com',
    storageBucket: 'alaa-3f713.firebasestorage.app',
    measurementId: 'G-VY49ED9PTK',
  );
}
